### ISSUE TITLE
Conference slides

### ISSUE THREAD

**Issue by kikislater** [osgeokorea/osgeokorea.github.io#1]
Hi, 

Thanks for this online conference.
Do you intend to host slides presented during this special foss4g ? 

Best regards,

Sylvain

**Comment by endofcap** [comment]
Hi Sylvain,

Surely we’ll do that. However it’ll take some days to collect all the presentation materials and publish them.

Cheers,
신상희
---
Shin, Sanghee
Gaia3D, Inc. - The GeoSpatial Company
www.gaia3d.com<http://www.gaia3d.com>

보낸 사람: Sylvain POULAIN<mailto:notifications@github.com>
보낸 날짜: 2020년 11월 14일 토요일 오전 12:05
받는 사람: osgeokorea/osgeokorea.github.io<mailto:osgeokorea.github.io@noreply.github.com>
참조: Subscribed<mailto:subscribed@noreply.github.com>
제목: [osgeokorea/osgeokorea.github.io] Conference slides (#1)


Hi,

Thanks for this online conference.
Do you intend to host slides presented during this special foss4g ?

Best regards,

Sylvain

**Comment by kikislater** [comment]
No problem, take your time ;-)
